name: Feature Request
description: File a new feature request
labels: ["feature"]
title: "[Feature] "
assignees:
  - Hndrxuprt
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the form below to submit your feature request.
  
  - type: dropdown
    id: request-type
    attributes:
      label: Type of feature request
      options:
        - Major new functionality
        - Improvement to existing feature
        - Small quality-of-life change
    validations: 
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the solution you'd like
      description: Please give a clear and concise description of what you want to happen.
      placeholder: "Example: I'd love to have an option to change the glow color based on spell school (Fire-red, Frost-blue, etc.)"
    validations:
      required: true
  - type: textarea
    id: feature-implementation
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: "Example: I've considered using 'X' for this, but it doesn't work with default buttons. In AddOn 'Y' I saw a similar animation called '...'"
    validations:
      required: true